### ISSUE TITLE
Only 1 node available in local ray even when I request more nodes

### ISSUE THREAD

**Issue by VolodyaCO** [zapatacomputing/orquestra-workflow-sdk#224]
## Describe the bug
I am trying to run several julia scripts using a python script that launches an SDK workflow. I request 3 nodes from the workflow resources, but my local machine would just run 1 task at a time instead of 3.

## How to Reproduce
A minimal example (without a `subprocess.run` call that triggers the julia program) is this one:
```python
import time

import orquestra.sdk as sdk
import numpy as np

CPU = "2000m"
MEMORY = "4Gi"
DISK = "1Gi"


@sdk.task(
    source_import=sdk.InlineImport(),
    resources=sdk.Resources(cpu=CPU, memory=MEMORY, disk=DISK),
)
def fun(seed: int, h: float):
    time.sleep(10)
    return {"msg": "I slept for 10 seconds"}


@sdk.workflow(resources=sdk.Resources(cpu=CPU, memory=MEMORY, disk=DISK, nodes=3))
def experiment():
    return [fun(seed=5, h=h) for h in np.linspace(0.5, 1.5, 20)]


if __name__ == "__main__":
    wf = experiment()
    wf_run = wf.run("ray")
    print(wf_run.run_id)
```

## Expected behavior
Since all my tasks are independent, I'd expect 3 nodes to run concurrently (I have a machine with 8 cores and 16 GB of memory)

## Actual behavior
This is what happens when I view the workflow:
```zsh
Workflow overview
-----------------  ------------------------
workflow def name  experiment
run ID             wf.experiment.c1086ac
status             RUNNING
start time         Fri Jun 30 20:14:40 2023
end time
tasks succeeded    3 / 20
-----------------  ------------------------

Task details
function    invocation ID           status     start_time                end_time                  message
----------  ----------------------  ---------  ------------------------  ------------------------  ---------
fun         invocation-0-task-fun   WAITING
fun         invocation-1-task-fun   WAITING
fun         invocation-2-task-fun   WAITING
fun         invocation-3-task-fun   WAITING
fun         invocation-4-task-fun   WAITING
fun         invocation-5-task-fun   WAITING
fun         invocation-6-task-fun   WAITING
fun         invocation-7-task-fun   WAITING
fun         invocation-8-task-fun   WAITING
fun         invocation-9-task-fun   WAITING
fun         invocation-10-task-fun  WAITING
fun         invocation-11-task-fun  WAITING
fun         invocation-12-task-fun  WAITING
fun         invocation-13-task-fun  WAITING
fun         invocation-14-task-fun  WAITING
fun         invocation-15-task-fun  WAITING
fun         invocation-16-task-fun  RUNNING    Fri Jun 30 20:15:52 2023
fun         invocation-17-task-fun  SUCCEEDED  Fri Jun 30 20:15:42 2023  Fri Jun 30 20:15:52 2023
fun         invocation-18-task-fun  SUCCEEDED  Fri Jun 30 20:15:32 2023  Fri Jun 30 20:15:42 2023
fun         invocation-19-task-fun  SUCCEEDED  Fri Jun 30 20:15:22 2023  Fri Jun 30 20:15:32 2023
```

## Environment (please complete the following information):**
 - OS: OSX 13.3.1 w/ M1 chip
 - Python version: 3.9.16

## Additional context
I ran this (using `subprocess.run` to run my julia program) on a linux cluster with 38 cores and it works as expected.

**Comment by jamesclark-Zapata** [comment]
@VolodyaCO workflow resources (and `nodes`) are only available on CE, not locally.

On your own machine, Ray will scale up to the amount of resources that are available in the local cluster, which by default is determined by the resources of your machine.

I ran it on my laptop and saw that it was running sequentially (as you saw), but I reduced the memory from `4Gi` to `1Gi` and I was able to run 4 tasks at once.
<img width="803" alt="Screenshot 2023-07-03 at 10 48 20" src="https://github.com/zapatacomputing/orquestra-workflow-sdk/assets/70290797/b5002e00-944a-47a4-b2ee-47ad5015262a">

If you're meaning to run on CE, then you'll have to switch out the `.run("ray")` to match the cluster you want to run on.

If you're intending to run locally and for some reason Ray's not picking up the resources of your laptop, then let us know and we can look and see why.

**Comment by VolodyaCO** [comment]
@jamesclark-Zapata so does this mean that locally the workflow resources are ignored? or is just the `nodes` part that gets ignored?

**Comment by jamesclark-Zapata** [comment]
`@sdk.workflow(resources=...)` is for CE only. This is because, locally, we can't dynamically change the resources the Ray cluster has (at least the way we have things setup, it may be possible somehow in Ray).
Locally, the available workflow resources are set by Ray when you do `orq up`.

`@sdk.task(resources=...)` are applied locally in Ray and remotely on CE.

---

[Hopefully these docs will help](https://docs.orquestra.io/docs/core/sdk/guides/resource-management.html#setting-workflow-resources), but if not, lmk!

**Comment by VolodyaCO** [comment]
Ok, so I will remove the resource specification in the `sdk.workflow` decorator to see if this runs as expected. Also, there seems to be an issue with terminating workflows whose tasks create processes with `subprocess.run`. I launched a bunch of processes in tasks using `subprocess.run`, but when I do `orq workflow stop [id]`, the processes are not killed and I need to kill them manually. I think it would be useful if `orq wf stop` found the child processes of the main Python process that spawns each task and kills them all

**Comment by jamesclark-Zapata** [comment]
I don't expect changing `sdk.workflow` to make any difference locally, it's not used.

for the other problem, can you post on Slack some details? Otherwise I'll close this issue.
